"""init-setup

Revision ID: 07e72d5d2967
Revises: b0ab86b09df4
Create Date: 2025-07-11 08:38:13.846490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07e72d5d2967'
down_revision: Union[str, Sequence[str], None] = 'b0ab86b09df4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('date_created', sa.String(length=100), nullable=False))
    op.drop_column('users', 'created_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created_date', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_column('users', 'date_created')
    # ### end Alembic commands ###
