"""create-chat-models

Revision ID: 11c4a7d7f846
Revises: 07e72d5d2967
Create Date: 2025-07-22 21:21:15.862378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '11c4a7d7f846'
down_revision: Union[str, Sequence[str], None] = '07e72d5d2967'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('sender_id', sa.Integer(), nullable=False))
    op.add_column('conversations', sa.Column('receiver_id', sa.Integer(), nullable=False))
    op.create_unique_constraint('unique_conversation', 'conversations', ['sender_id', 'receiver_id'])
    op.drop_constraint(op.f('conversations_created_by_fkey'), 'conversations', type_='foreignkey')
    op.create_foreign_key(None, 'conversations', 'users', ['sender_id'], ['id'])
    op.create_foreign_key(None, 'conversations', 'users', ['receiver_id'], ['id'])
    op.drop_column('conversations', 'created_at')
    op.drop_column('conversations', 'name')
    op.drop_column('conversations', 'created_by')
    op.drop_column('conversations', 'is_group')
    op.add_column('message_status', sa.Column('recipient_id', sa.Integer(), nullable=False))
    op.add_column('message_status', sa.Column('delivered_at', sa.DateTime(), nullable=True))
    op.add_column('message_status', sa.Column('read_at', sa.DateTime(), nullable=True))
    op.create_unique_constraint(None, 'message_status', ['message_id'])
    op.drop_constraint(op.f('message_status_user_id_fkey'), 'message_status', type_='foreignkey')
    op.create_foreign_key(None, 'message_status', 'users', ['recipient_id'], ['id'])
    op.drop_column('message_status', 'seen_at')
    op.drop_column('message_status', 'user_id')
    op.add_column('users', sa.Column('email', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('password_hash', sa.Text(), nullable=False))
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('users', sa.Column('last_seen', sa.DateTime(), nullable=True))
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=250),
               type_=sa.Text(),
               existing_nullable=False)
    op.create_unique_constraint(None, 'users', ['email'])
    op.drop_column('users', 'date_created')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('date_created', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'username',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=250),
               existing_nullable=False)
    op.drop_column('users', 'last_seen')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'password_hash')
    op.drop_column('users', 'email')
    op.add_column('message_status', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('message_status', sa.Column('seen_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'message_status', type_='foreignkey')
    op.create_foreign_key(op.f('message_status_user_id_fkey'), 'message_status', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'message_status', type_='unique')
    op.drop_column('message_status', 'read_at')
    op.drop_column('message_status', 'delivered_at')
    op.drop_column('message_status', 'recipient_id')
    op.add_column('conversations', sa.Column('is_group', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('conversations', sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('conversations', sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('conversations', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.create_foreign_key(op.f('conversations_created_by_fkey'), 'conversations', 'users', ['created_by'], ['id'])
    op.drop_constraint('unique_conversation', 'conversations', type_='unique')
    op.drop_column('conversations', 'receiver_id')
    op.drop_column('conversations', 'sender_id')
    # ### end Alembic commands ###
