"""sync users columns

Revision ID: 75757c160ca1
Revises: 11c4a7d7f846
Create Date: 2025-12-26 22:03:05.471939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75757c160ca1'
down_revision: Union[str, Sequence[str], None] = '11c4a7d7f846'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_pic', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('sex', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('pfp_url', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('hobbies', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('bio', sa.Text(), nullable=True))
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('users', 'bio')
    op.drop_column('users', 'hobbies')
    op.drop_column('users', 'pfp_url')
    op.drop_column('users', 'sex')
    op.drop_column('users', 'age')
    op.drop_column('users', 'profile_pic')
    # ### end Alembic commands ###
